spring.application.name=backend-pacifica-saas

# ===================================================================
# Configuración de Base de Datos (PostgreSQL)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/pacificadb
spring.datasource.username=admin
spring.datasource.password=supersecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# Configuración de JPA / Hibernate
# ===================================================================

# update: Crea/actualiza las tablas automáticamente basándose en tus Entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# Flyway (Desactivado para desarrollo con BD en memoria)
# ===================================================================
spring.flyway.enabled=false

# ===================================================================
# Configuración de Seguridad JWT
# ===================================================================
pacifica.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
pacifica.security.jwt.expiration=86400000 
# 86400000 milisegundos = 24 horas

#N8N password = Password123